name: Generate Permanent Android Keystore

on:
  workflow_dispatch:

jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore Natively
        run: |
          keytool -genkeypair -v -keystore release.keystore -alias upload -keyalg RSA -keysize 2048 -validity 10000 -storepass capacitorpass123 -keypass capacitorpass123 -dname "CN=Android Build,O=Capacitor,C=US"
          echo "============================================="
          echo " COPY THE TEXT STRIP BELOW FOR YOUR SECRET: "
          echo "============================================="
          base64 -w 0 release.keystore
          echo ""
          echo "============================================="
